# Generated by Django 2.2.5 on 2019-09-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='events',
            field=models.ManyToManyField(to='eventFinderApp.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
