# Generated by Django 2.2.5 on 2019-09-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0002_auto_20190904_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='events',
        ),
        migrations.AddField(
            model_name='category',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventFinderApp.Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
