# Generated by Django 2.2.4 on 2019-09-25 12:04
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0002_event_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='end date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='start date'),
            preserve_default=False,
        ),
    ]
